title: LEE BUI FAH
#logo: /assests/profile.jpg
#description: Outside of work and studies, I maintain an active lifestyle through regular gym sessions and continuously seek opportunities for personal and professional growth.
theme: jekyll-theme-minimal 
